### PR TITLE
feat: implement FranceConnect

### PR DESCRIPTION
**Pull request by btrd**
https://github.com/betagouv/civilsdeladefense/issues/431

### CODE REVIEW

**Comment by yannski** [comment]
@btrd le logout ne fonctionne pas - erreur du côté FC. Normal ?

**Review by yannski — CHANGES_REQUESTED** [review]
@btrd  can you rebase?

**Comment by ssoulless** [comment]
Not sure how this is working as per the docs of the omniauth_openid_connect gem:

> NOTE: if you use this gem with Devise you should use :openid_connect name, or Devise would route to 'users/auth/:provider' rather than 'users/auth/openid_connect'

Any additional stuff you did to make it work with devise with your custom `name:` provider?

**Comment by btrd** [comment]
Not that I remember sorry :/

**Pull request merged**
